import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

function log(msg: string) {
  console.log(`\x1b[36m[SHER SETUP]\x1b[0m ${msg}`);
}

function success(msg: string) {
  console.log(`\x1b[32m[✓ SUCCESS]\x1b[0m ${msg}`);
}

function warn(msg: string) {
  console.log(`\x1b[33m[⚠ NOTE]\x1b[0m ${msg}`);
}

async function run() {
  console.log("\n=======================================================");
  console.log("   SHER-MESSENGER v2 — 1-Click Auto Setup & Deploy");
  console.log("   ₹0 Free-Tier · Zero-Knowledge · Cloudflare Edge");
  console.log("=======================================================\n");

  const isDeploy = process.argv.includes("--deploy") || process.argv.includes("-d");

  // 1. Generate secrets
  log("Generating cryptographic session secrets and admin hash...");
  const adminPass = process.env.ADMIN_PASSWORD || crypto.randomBytes(8).toString("hex") + "A1!";
  const salt = crypto.randomBytes(16).toString("hex");
  const adminHash = `$pbkdf2-sha256$i=250000$${salt}$${crypto.pbkdf2Sync(adminPass, salt, 250_000, 32, "sha256").toString("hex")}`;
  const sessionSecret = crypto.randomBytes(32).toString("hex");

  // 2. Check / Setup Cloudflare D1
  let d1Id = "";
  try {
    log("Checking Cloudflare D1 database (sher-ops)...");
    const d1Out = execSync("npx wrangler d1 list --json", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    const d1List = JSON.parse(d1Out);
    const existingD1 = d1List.find((d: any) => d.name === "sher-ops");
    if (existingD1) {
      d1Id = existingD1.uuid;
      success(`Found existing D1 database 'sher-ops': ${d1Id}`);
    }
  } catch {}

  if (!d1Id) {
    try {
      log("Creating Cloudflare D1 database 'sher-ops'...");
      const out = execSync("npx wrangler d1 create sher-ops", { encoding: "utf8" });
      const match = out.match(/database_id\s*=\s*"([^"]+)"/);
      if (match && match[1]) {
        d1Id = match[1];
        success(`Created D1 database 'sher-ops': ${d1Id}`);
      }
    } catch {
      warn("D1 create skipped or not logged into wrangler. You can configure D1 or Neon manually.");
    }
  }

  // 3. Check / Setup Cloudflare KV
  let kvId = "";
  try {
    log("Checking Cloudflare KV namespace (sher-rl)...");
    const kvOut = execSync("npx wrangler kv namespace list", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    const kvList = JSON.parse(kvOut);
    const existingKv = kvList.find((k: any) => k.title === "sher-messenger-sher-rl" || k.title === "sher-rl");
    if (existingKv) {
      kvId = existingKv.id;
      success(`Found existing KV namespace 'sher-rl': ${kvId}`);
    }
  } catch {}

  if (!kvId) {
    try {
      log("Creating Cloudflare KV namespace 'sher-rl'...");
      const out = execSync("npx wrangler kv namespace create sher-rl", { encoding: "utf8" });
      const match = out.match(/id\s*=\s*"([^"]+)"/);
      if (match && match[1]) {
        kvId = match[1];
        success(`Created KV namespace 'sher-rl': ${kvId}`);
      }
    } catch {
      warn("KV create skipped. Rate limits will use volatile RAM fallback.");
    }
  }

  // 4. Update wrangler.toml with keep_vars, D1, and KV bindings
  const wranglerPath = path.join(process.cwd(), "wrangler.toml");
  if (fs.existsSync(wranglerPath)) {
    let toml = fs.readFileSync(wranglerPath, "utf8");
    if (!toml.includes("keep_vars = true")) {
      toml = toml.replace('workers_dev = true', 'workers_dev = true\n\nkeep_vars = true');
    }
    if (d1Id && !toml.includes("database_name = \"sher-ops\"")) {
      toml += `\n\n[[d1_databases]]\nbinding = "DB"\ndatabase_name = "sher-ops"\ndatabase_id = "${d1Id}"`;
    }
    if (kvId && !toml.includes("binding = \"KV\"")) {
      toml += `\n\n[[kv_namespaces]]\nbinding = "KV"\nid = "${kvId}"`;
    }
    fs.writeFileSync(wranglerPath, toml, "utf8");
    success("wrangler.toml updated with keep_vars = true, D1, and KV bindings");
  }

  // 5. Update .env if missing
  const envPath = path.join(process.cwd(), ".env");
  if (!fs.existsSync(envPath)) {
    const envContent = `# Auto-generated by SHER 1-Click Setup
ADMIN_EMAIL="admin@example.com"
ADMIN_PASSWORD="${adminPass}"
ADMIN_PASSWORD_HASH="${adminHash}"
ADMIN_PATH="sh3r-9x-admin"
SESSION_SECRET="${sessionSecret}"
PUBLIC_APP_NAME="Sher Messenger"
PUBLIC_UI_LANG_DEFAULT="hi"
ROOM_TTL_DEFAULT_MIN="30"
ROOM_TTL_HARD_CAP_MIN="120"
D1_DATABASE_ID="${d1Id}"
KV_NAMESPACE_ID="${kvId}"
`;
    fs.writeFileSync(envPath, envContent, "utf8");
    success(".env created with generated credentials");
  }

  console.log("\n=======================================================");
  console.log("            ✨ Setup Summary & Credentials");
  console.log("=======================================================");
  console.log(`Admin Route     : /sh3r-9x-admin`);
  console.log(`Admin Email     : admin@example.com`);
  console.log(`Admin Password  : ${adminPass}`);
  console.log(`D1 Database ID  : ${d1Id || "(Manual/Neon/Turso configured)"}`);
  console.log(`KV Namespace ID : ${kvId || "(Memory fallback active)"}`);
  console.log("=======================================================\n");

  if (isDeploy) {
    log("Building and deploying to Cloudflare...");
    try {
      execSync("npx opennextjs-cloudflare build && npx wrangler deploy", { stdio: "inherit" });
      success("Deployed successfully to Cloudflare Pages & Workers!");
    } catch (e: any) {
      console.error("\x1b[31m[Deploy Error]\x1b[0m", e.message);
    }
  } else {
    log("To deploy in 1 click, run: npm run deploy:oneclick");
  }
}

run().catch(console.error);
